version: '3'

services:
#  api:
#    container_name: 'jibbyjabber'
#      build:
#        context: .
#        dockerfile: Dockerfile
#      ports:
#        - 8080:8080
#      environment:
#        DB_USER: postgres
#        DB_PASSWORD: password
#        DB_NAME: compose-db
#        DB_HOST: postgres_db
#        DB_PORT: 5432

  db:
    image: library/postgres:9.6
    container_name: 'postgresJibby'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jibby
      volumes:
        /var/lib/postgresql/data