openapi: 3.0.1
info:
  description: "This is a sample Social media. \n"
  version: 1.0.0
  title: Jibby Jabber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
- name: post
  description: Access to Posts
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  /post/{userId}:
    post:
      tags:
      - post
      summary: Create post
      description: This can only be done by the logged in user.
      operationId: createPost
      parameters:
      - name: userId
        in: path
        description: userId that wants to post
        required: true
      - in: body
        name: body
        description: Post post object
        required: true
        schema:
          $ref: '#/definitions/Post'
      responses:
        "400":
          description: Invalid userId supplied
        "404":
          description: User not found
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        userId:
          type: integer
          format: int64
        text:
          type: string
        date:
          type: integer
          format: int64
      required:
        - name
        - clientId
        - text
        - date

